Pipes should fail if any part fails
This uses a new shell function pipe_or_die to simulate the behavior of
'set -o pipefail'. If any command in a pipeline fails, the program
exits.

diff --git a/config-files/.local/bin/battstats b/config-files/.local/bin/battstats
--- a/config-files/.local/bin/battstats
+++ b/config-files/.local/bin/battstats
@@ -38,10 +38,32 @@ warn_printf() {
   )
 }
 
+pipe_or_die() (
+if [ $# = 0 ]; then
+  printf '%s: pipe_or_die: internal error: invalid usage\n' "${bname}" >&2
+  kill -- "${self}" || {
+    printf '%s: pipe_or_die: internal error: failed to kill self\n' "${bname}" >&2
+  }
+  exit 3
+fi
+
+command_name="$1"
+
+"$@" || {
+  printf '%s: %s: command failed\n' "${bname}" "${command_name}" >&2
+  kill -- "${self}" || {
+    printf '%s: pipe_or_die: internal error: failed to kill self\n' "${bname}" >&2
+  }
+  exit 3
+}
+)
+
 bname="$(basename -- "$0")" || {
   bname="$0"
   warn 'basename failed'
 }
+
+self="$$"
 
 print_help() (
 printf 'usage: %s [-h] [-d power-directory]\n' "${bname}" >&2
@@ -97,7 +119,7 @@ fi
 # no power supplies.
 
 is_first_line=true
-ls -1A -- "${power_dir}"/. | while read -r power_supply; do
+pipe_or_die ls -1A -- "${power_dir}"/. | while read -r power_supply; do
   power_supply="${power_dir}"'/'"${power_supply}"
 
   if [ -f "${power_supply}"'/type' ]; then
diff --git a/install b/install
--- a/install
+++ b/install
@@ -8,8 +8,30 @@ bname="$(basename -- "$0")" || {
   exit 1
 }
 
+self="$$"
+
 print_usage() (
 printf 'usage: %s [-s source-dir] [-t target-dir]\n' "${bname}" >&2
+)
+
+pipe_or_die() (
+if [ $# = 0 ]; then
+  printf '%s: pipe_or_die: internal error: invalid usage\n' "${bname}" >&2
+  kill -- "${self}" || {
+    printf '%s: pipe_or_die: internal error: failed to kill self\n' "${bname}" >&2
+  }
+  exit 3
+fi
+
+command_name="$1"
+
+"$@" || {
+  printf '%s: %s: command failed\n' "${bname}" "${command_name}" >&2
+  kill -- "${self}" || {
+    printf '%s: pipe_or_die: internal error: failed to kill self\n' "${bname}" >&2
+  }
+  exit 3
+}
 )
 
 install_directory() (
@@ -21,7 +43,7 @@ fi
 source_folder="$1"
 dest_folder="$2"
 
-ls -A1 -- "${source_folder}" | while read -r entry; do
+pipe_or_die ls -A1 -- "${source_folder}" | while read -r entry; do
   entry_path="${source_folder}"/"${entry}"
   if ! [ -e "${entry_path}" ]; then
     printf '%s: could not find file %s\n' "${bname}" "${entry_path}" >&2
